export const OFFERS = [
    { name: "Service A", serviceType: "Portrait photoshoot.", description: "Capture your personality and style with professional portrait photography. Whether for business, social media, or personal keepsakes, we create timeless, high-quality portraits that showcase your best self.", price: 100, imgFile: "portraitPhoto.jpg" },
    { name: "Service B", serviceType: "Wedding photoshoot.", description: "Relive your special day forever with stunning wedding photography. We capture every heartfelt moment, from the vows to the dance floor, ensuring your love story is told beautifully.", price: 200, imgFile: "weddingPhoto.jpg" },
    { name: "Service C", serviceType: "Vacation photoshoot.", description: "Turn your travels into unforgettable memories with professional vacation photography. Enjoy the moment while we document your adventure with breathtaking shots in stunning locations.", price: 150, imgFile: "vacationPhoto.jpg"},
    { name: "Service D", serviceType: "Sport photoshoot.", description: "Freeze the action with high-energy sports photography. Whether it’s a game-winning goal or an intense workout session, we capture the passion, speed, and determination of every moment", price: 180, imgFile: "sportPhoto.jpg"},
    { name: "Service E", serviceType: "Science photoshoot.", description: "Bring science to life through compelling imagery. From lab experiments to field research, we document scientific processes and discoveries with precision and creativity.", price: 280, imgFile: "sciencePhoto.jpg"},
    { name: "Service F", serviceType: "Poledance photoshoot.", description: "Showcase the strength, grace, and artistry of pole dance with dynamic photography. We highlight your movement, flexibility, and expression in stunning, empowering images.", price: 120, imgFile: "poledancePhoto.jpg"},
    { name: "Service G", serviceType: "Landscape photoshoot.", description: "Discover the beauty of nature through breathtaking landscape photography. From majestic mountains to serene beaches, we capture the essence of the world’s most stunning scenery.", price: 150, imgFile: "landscapePhoto.jpg"},
    { name: "Service H", serviceType: "Fine Art photoshoot.", description: "Transform ideas into artistic masterpieces with fine art photography. We craft visually striking, thought-provoking images that evoke emotion and tell unique stories.", price: 120, imgFile: "fineArtPhoto.jpg"},
    { name: "Service I", serviceType: "Animal photoshoot.", description: "Celebrate the beauty and personality of your pets or wildlife with professional animal photography. Whether playful, majestic, or wild, we capture animals in their best light.", price: 120, imgFile: "animalPhoto.jpg"},
  ];
  